project:
  type: website

website:
  title: "borea17"

  page-navigation: true

  sidebar:
    id: paper-summaries
    title: Paper Summaries
    style: "docked"
    background: light
    collapse-level: 2

  navbar:
    background: primary
    search: true
    right:
      - href: index.qmd
        text: Home
      - about.qmd
      - paper_summaries.qmd
    # left:
    #   - text: "Home"
    #     file: index.qmd
    #   - sidebar:paper-summaries

    # left:
    #   - href: index.qmd
    #     text: Home
    #   - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



