project:
  type: website
  preview:
    port: 8080

website:
  title: "borea17"

  page-navigation: true

  # sidebar:
  #   id: paper-summaries
  #   title: Paper Summaries
  #   style: "docked"
  #   background: light
  #   collapse-level: 2


  navbar:
    background: "#607d8b"
    search: true
    right:
      - paper_summaries.qmd
      - ml101.qmd
    # left:
    #   - text: "Home"
    #     file: index.qmd
    #   - sidebar:paper-summaries

    # left:
    #   - href: index.qmd
    #     text: Home
    #   - about.qmd

format:
  html:
    theme: default
    css: styles.css
    toc: true



