project:
  type: website
  preview:
    port: 8080
  output-dir: docs

website:
  title: "borea17"
  site-url: "https://borea17.github.io/"
  page-navigation: true
  favicon: logo.png


  navbar:
    background: "#607d8b"
    search: true
    right:
      - paper_summaries.qmd
      - ml101.qmd

format:
  html:
    theme: default
    css: styles.css
    toc: true



